# certificate.yml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudcomputingchat-ca-tsl
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - testorganization
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - cloudcomputingchat.pt
    - api.cloudcomputingchat.pt
    - storage.cloudcomputingchat.pt
  secretName: cloudcomputingchat-ca-tsl
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io