apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudcronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cloudcronjob
            image: sapasboss/cloudcronjob
            imagePullPolicy: Always